# https://taskfile.dev
version: '3'


dotenv:
  - .env


vars:
  PY_PREFIX:
    sh: if [[ ${POETRY_ACTIVE:-} != "1" ]]; then echo "poetry run"; fi


tasks:
  ci:
    desc: Run all tasks required to merge code into the main branch
    cmds:
      - task: ruff:check
      - task: mypy
      - task: pytest

  ruff:check:
    desc: Check linting and formatting of Python sources with `astral-sh/ruff`.
    cmds:
      - "{{.PY_PREFIX}} ruff check {{.CLI_ARGS}} hohh"
      - "{{.PY_PREFIX}} ruff format --check {{.CLI_ARGS}} hohh"

  ruff:fix:
    desc: Fix linting errors in Python sources with `astral-sh/ruff`.
    cmds:
      - "{{.PY_PREFIX}} ruff check --fix {{.CLI_ARGS}} hohh"

  ruff:format:
    desc: Fix formatting of Python sources with `astral-sh/ruff`.
    cmds:
      - "{{.PY_PREFIX}} ruff format {{.CLI_ARGS}} hohh"

  mypy:
    desc: Run python/mypy Python type checking tool
    sources:
      - ./**/*.py
    cmds:
      - "{{.PY_PREFIX}} mypy {{.CLI_ARGS}} ./hohh"

  pytest:
    desc: Run unit tests via pytest-dev/pytest
    sources:
      - ./**/*.py
    cmds:
      - "{{.PY_PREFIX}} pytest {{.CLI_ARGS}} ./hohh"

  hohh:
    cmds:
      - "{{.PY_PREFIX}} python -m hohh {{.CLI_ARGS}}"
